### ISSUE TITLE
chore: 프로젝트 초기 세팅

### ISSUE THREAD

**Issue by Ryooon2** [KooK-PaP/kook-Pap-Server#1]
## IssueName
프로젝트 초기 세팅
## Description
세팅할거다.
## Todo
- [x] Spring Boot Initializer로 프로젝트 생성
- [x] depandancy 주입
- [x] git ignore 설정
- [x] properties 설정
- [x] 디렉터리 구조 설정
