### ISSUE TITLE
feat: 어플리케이션 응답 객체, 전역 Exception 설정

### ISSUE THREAD

**Issue by Ryooon2** [KooK-PaP/kook-Pap-Server#10]
## IssueName
어플리케이션 응답 객체, 전역 Exception 설정
### 어플리케이션 응답객체
- 정상적으로 응답시 사용할 DTO, ApplicationResponse 클래스 구현
- 에러시에 사용할 DTO, ApplicationErrorResponse 클래스 구현

### 전역 Exception
- 에러 코드로 사용할 ErrorCode  Enum 구현
- ErrorCode로 표현한 exception, CustomException 구현
- CustomException을 처리할 CustomExceptionHandler 구현

### JWT 필터 도중 발생한 인증 에러
- JwtTokenProvider에서 토큰 검증시, 상황에 맞게 CustomException throw하도록 수정
- JwtFilter에서 CustomException을 캐치하여 CustomAuthenticationEntryPoint으로 ErrorCode 전달 할 수 있도록 수정
- CustomAuthenticationEntryPoint에서 ApplicationErrorResponse와 ErrorCode를 토대로 response를 생성하도록 수정

## Todo
- [x] ApplicationReponse 구현
- [x] ApplicationErrorResponse 구현
- [x] ErrorCode 구현
- [x] CustomException 구현
- [x] CustomExceptionHandler 구현
- [x] JwtFilter 로직 수정
- [x] JwtTokenProvider 로직 수정
- [x] CustomAuthenticationEntryPoint 로직 수정
