### ISSUE TITLE
feat: entity 재설정

### ISSUE THREAD

**Issue by Ryooon2** [KooK-PaP/kook-Pap-Server#12]
## IssueName
entity 재설정
## Description
[erd 사진](https://github.com/KooK-PaP/kook-Pap-Server/wiki/ERD)
- 기존에 Restaurant 테이블에 있던 영업시간을 따로 분리.
- 주문로직 추가로 Bucket entity와 Order entity를 새로 생성.
- 주문 로직을 위해 Member에 address column을 추가.
## Todo
- [x] Bucket entity 작성
- [x] Order entity 작성
- [x] Operation entity 작성
- [x] Member에 address column 추가
