### ISSUE TITLE
feat: Entity 생성 및 참조 관계 연동

### ISSUE THREAD

**Issue by dl-00-e8** [KooK-PaP/kook-Pap-Server#2]
## IssueName

Entity 생성 및 참조 관계 연동

## Description

설계한 ERD에 맞춘 Entity 생성 및 참조 관계 연동

## Todo

- [ ] Member Entity 생성
- [ ] Restaurant Entity 생성
- [ ] Menu Entity 생성
- [ ] Review Entity 생성
