### ISSUE TITLE
feat: Restaurant API 개발

### ISSUE THREAD

**Issue by dl-00-e8** [KooK-PaP/kook-Pap-Server#20]
## IssueName

Restaurant API 개발

## Description

Restaurant 도메인 관련 API 개발
[API 명세서](https://reliable-copper-d92.notion.site/83ca4930f4a44b098f53032545bf22a3?v=528add96b8324066bf4f454577458598&pvs=4) 기반으로 개발 진행
Operation Entity 자료형 String에서 LocalTime으로 수정 -> 추후 영업 시간 기반 정렬 또는 필터링 시 활용하기 위함

## Todo

- [x] Operation Entity 수정
- [x] 가게 등록 API
- [x] 가게 정보 수정 API
- [x] 가게 삭제 API
- [x] 내 모든 가게 정보 반환 API
- [x] 특정 가게 정보 반환 API
