### ISSUE TITLE
test: Restaurant 테스트 코드 개발

### ISSUE THREAD

**Issue by dl-00-e8** [KooK-PaP/kook-Pap-Server#23]
## IssueName

Restaurant 테스트 코드 개발

## Description

Restaurant API 개발 완료됨에 따라, 관련 성공/실패/에러 등에 대한 테스트 코드를 개발하여, 추후 확장하는 과정에서 테스트 코드로 변경사항에 대한 검증을 하고자 함.

## Todo

- [ ] Restaurant 등록 API 성공/실패 테스트 코드 작성
- [ ] Restaurant 수정 API 성공/실패 테스트 코드 작성
- [ ] Restaurant 삭제 API 성공/실패 테스트 코드 작성
- [ ] 특정 Restaurant 반환 API 성공/실패 테스트 코드 작성
- [ ] 내 Restaurant 리스트 반환  API 성공/실패 테스트 코드 작성
