### ISSUE TITLE
feat: 스프링 시큐리티 & JWT 필터 추가

### ISSUE THREAD

**Issue by Ryooon2** [KooK-PaP/kook-Pap-Server#9]
## IssueName
스프링 시큐리티 & JWT 필터 추가
## Description
1. JWT 인증 방식에 적합하도록 security 설정.
2. JWT 토큰 관리 클래스 작성.
3. JWT 필터 작성.
4. Authentication 객체에 전달할 UserDetails 구현체 작성.
5. 시큐리티 필터 체인 도중 발생하는 예외 처리 핸들러 작성.

## Todo
- [x] JWT관련 의존성 추가
- [x] SecurityConfig 구현
- [x] JwtSecurityConfig 구현
- [x] JwtTokenProvider (JWT 토큰 관리 클래스) 구현
- [x] PrincipalDetails (UserDetails 구현체) 구현
- [x] JwtFilter 구현
- [x] CustomAuthenticationEntryPoint 구현
- [x] CustomAccessDeniedHandler 구현

### JWT관련 의존성
![image](https://github.com/KooK-PaP/kook-Pap-Server/assets/138233569/2424f10e-0d5f-4780-b865-837d2bad4170)
위 사진 처럼 JWT에 관련된 라이브러리를 추가하였습니다.

### SecurityConfig
![2023-08-27 20 48 14](https://github.com/KooK-PaP/kook-Pap-Server/assets/138233569/85c3cd6c-1ed0-47be-abe3-c8ce0ab30487)
위 클래스는 전반적인 spring security에 대한 설정을 작성하는 클래스 입니다.

1. JWT 인증 방식을 채택하고 있기 때문에 CSRF 방지 기능, session, httpBasic, formLogin을 비활성화하였습니다.
2. pre-flight를 고려하여 HttpMethod.OPTIONS을 허용하였습니다. 
3. 다만 아직 서버 로직이 미구현 상태이기 때문에 URL 접근성에 대해서는 아직 제대로 설정하지는 않았습니다.
4. accessDeniedHandler로 **CustomAccessDeniedHandler**를, authenticationEntryPoint로 **CustomAuthenticationEntryPoint**를 지정하였습니다.
5. jwt 시큐리티 설정(JwtSecurityConfig)을 apply 해주었습니다.
6. 또 추가적으로 CORS 관련 설정인 corsConfigurationSource를 작성하였습니다.

### JwtSecurityConfig
![image](https://github.com/KooK-PaP/kook-Pap-Server/assets/138233569/3e099b13-a839-41ce-91db-48d6bfdd3070)
위 클래스는 spring security에서 JWT가 필요한 설정을 지정하는 클래스로,
여기서는 JwtFilter를 UsernamePasswordAuthenticationFilter 앞에 추가하였습니다.

따라서 전통적인 Id와 Pw로 인증을 하는 것이 아닌, JWT 토큰을 이용한 인증방식으로 시큐리티가 동작하게 됩니다.

### JwtTokenProvider
![asdf](https://github.com/KooK-PaP/kook-Pap-Server/assets/138233569/79c6d37c-1b32-42c0-b6b9-ac195cfd78b9)

위 클래스는 Jwt token을 관리하는 클래스입니다. 

주요 메서드로는 토큰 생성, 토큰으로 Authentication객체 생성, 토큰 유효성 검사가 있습니다.

메서드 설명:
**generateJwtTokenDto** : 
access 토큰은 3시간, refresh 토큰은 일주일의 유효시간을 가지도록 생성되며, JwtTokenDto 객체에 담겨서 반환됩니다.
access 토큰의 subject로 member의 email을, claim으로는 id와 name을 가지도록 설정하였습니다.

**getAuthentication** :
access 토큰으로 member 객체를 DB로부터 꺼내오고, 해당 member 객체를 토대로 PrincipalDetails 생성합니다.
이 PrincipalDetails 객체를 바탕으로 Authentication객체를 생성 후, 반환합니다.

**validateToken** :
토큰의 유효성 검사를 진행하고 유효하면 true, 유효하지 않으면 AuthenticationServiceException을 throw합니다.

### PrincipalDetails
![image](https://github.com/KooK-PaP/kook-Pap-Server/assets/138233569/d33527ff-8238-4b66-b18b-bc74e99e7e7c)
Authentication객체에 사용자 정보를 담기 위한 UserDetails 구현체입니다.
내부 필드로 Member를 가집니다.

### JwtFilter
![image](https://github.com/KooK-PaP/kook-Pap-Server/assets/138233569/ab74b77b-e5eb-4f88-91a5-4d33c1b1a365)
HttpServletRequest에 존재하는 JWT 토큰을 토대로 인증 작업을 수행하는 클래스입니다.

doFilterInternal 메서드는 jwt 토큰이 유효하면 JwtTokenProvider를 통해 만든 Authentication객체를 SecurityContextHolder에 저장합니다.

### CustomAccessDeniedHandler
![image](https://github.com/KooK-PaP/kook-Pap-Server/assets/138233569/19b330d2-8396-48de-a2c4-c34e7d9d99b7)
해당 클래스는 리소스에 대한 자격을 갖추지 않은 접근에 대한 처리를 하는 클래스입니다.
accessDeniedException을 토대로 response를 생성합니다.

### CustomAuthenticationEntryPoint
![image](https://github.com/KooK-PaP/kook-Pap-Server/assets/138233569/98408a7e-a70e-401c-928b-966898a98b3d)
해당 클래스는 인증 도중 발생한 에러를 처리하는 클래스입니다.
AuthenticationException을 토대로 response를 생성합니다.
